POST http://localhost:3000/api/persons
Content-type: application/json

{
    "name": "cev",
    "number": "508-649-FUCK"
}
###
POST http://localhost:3000/api/persons
Content-type: application/json

{
    "name": "cev"
}
###
POST http://localhost:3000/api/persons
Content-type: application/json

{
    "number": "508-649-FUCK"
}
